services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080" 
    environment:
      - DATABASE_URL=${DATABASE_URL}
    entrypoint: ["./bin/server"]

  inspector:
    image: node:23-alpine
    ports:
      - "6274:6274"  # Inspector UI
      - "6277:6277"  # Inspector proxy
    working_dir: /app
    volumes:
      - ./inspector_node_modules:/app/node_modules
    environment:
      - MCP_INSPECTOR_DEFAULT_SERVER_URL=http://server:8080/mcp
    command: sh -c "npm install @modelcontextprotocol/inspector@0.12.0 && npx @modelcontextprotocol/inspector"
    depends_on:
      - server

volumes:
  inspector_node_modules: